// workspace.js - Zero-copy local file system management

const DB_NAME = 'EngineWorkspaceDB';
const STORE_NAME = 'WorkspaceStore';
const KEY_NAME = 'root_dir_handle';

// Open IndexedDB using native API
function openDatabase() {
	return new Promise((resolve, reject) => {
		const request = indexedDB.open(DB_NAME, 1);
		request.onupgradeneeded = (e) => {
			e.target.result.createObjectStore(STORE_NAME);
		};
		request.onsuccess = (e) => resolve(e.target.result);
		request.onerror = (e) => reject(e.target.error);
	});
}

// 1. Initial setup: User explicitly selects the game folder
export async function selectWorkspaceDirectory() {
	try {
		const handle = await window.showDirectoryPicker({
			mode: 'readwrite'
		});

		const db = await openDatabase();
		const tx = db.transaction(STORE_NAME, 'readwrite');
		tx.objectStore(STORE_NAME).put(handle, KEY_NAME);

		return handle;
	} catch(err) {
		console.error("Directory selection cancelled or failed:", err);
		return null;
	}
}

// 2. Auto-load on page boot: Tries to reconnect without showing a picker dialog
export async function verifyAndGetWorkspace() {
	const db = await openDatabase();
	return new Promise((resolve) => {
		const tx = db.transaction(STORE_NAME, 'readonly');
		const req = tx.objectStore(STORE_NAME).get(KEY_NAME);

		req.onsuccess = async () => {
			const handle = req.result;
			if(!handle) {
				resolve(null); // User has never selected a folder yet
				return;
			}

			// Check if we still have permission (e.g. page refresh)
			const options = { mode: 'readwrite' };
			if(await handle.queryPermission(options) === 'granted') {
				resolve(handle);
				return;
			}

			// Permission lost (browser restart).
			// NOTE: You must call this specific function from a UI button click event handler!
			resolve(handle);
		};
		req.onerror = () => resolve(null);
	});
}

// 3. Request active permission on the saved handle (Must be inside a click handler)
export async function requestWorkspaceAccess(savedHandle) {
	const status = await savedHandle.requestPermission({ mode: 'readwrite' });
	return status === 'granted' ? savedHandle : null;
}

// 4. Zero-Copy Operations: Read/Write files directly on your hard drive
export async function manipulateGameFiles(dirHandle) {
	// Read a file directly from your local game directory straight into memory
	const fileHandle = await dirHandle.getFileHandle('pak0.pk3', { create: false });
	const file = await fileHandle.getFile();

	// This is an absolute pointer to the file data on disk (zero-copy buffer streaming)
	const buffer = await file.arrayBuffer();
	console.log(`Loaded ${file.name} directly from disk. Size: ${buffer.byteLength} bytes.`);

	// Write back changes directly to your local file system
	const configFileHandle = await dirHandle.getFileHandle('autoexec.cfg', { create: true });
	const writable = await configFileHandle.createWritable();
	await writable.write("// Generated by Illustrious Engine Layout\nseta r_customwidth 1920");
	await writable.close(); // Flushes data directly back to your hard drive
}
